# Generated by Django 5.2.4 on 2025-08-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_description_remove_movie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='movie/images/default.jpg', upload_to='movie/images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
